### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by jbsky** [kolzchut/mediawiki-extensions-GoogleUniversalAnalytics#1]
I'm newbie in using Media Wiki and I wish I configure Google Analytics.

I have set in LocalSettings $wgGoogleAnalyticsAccount="UA-XXXXXXXXX-X"; but I still have got this error :  < ! -- Error: you must set $wgGoogleAnalyticsAccount to your Google Analytics account number (e.g. "UA-12345678-1"). - -  >

**Comment by drorsnir** [comment]
Hi jbsky, this is a fork of https://www.mediawiki.org/wiki/Extension:Google_Analytics_Integration - unless you need some specific feature that's only available in this fork, I suggest you use the original.

Anyway, for __this fork__ the correct variable would be $wgGoogleUniversalAnalyticsAccount. Please read the README file, it is kept mostly up to date...

**Comment by jbsky** [comment]
So, now it works!?

Maybe you need update this error message.

Thank you for replying

**Comment by drorsnir** [comment]
You are correct - I just pushed through a change. Although it would be
better to merge my changes back to upstream.

דרור שניר
כל-זכות Dror Snir
All-Rights (Kol-Zchut)
www.kolzchut.org.il
